2024-12-08 21:19:08,328 | INFO | "test_challenge" выполнен успешно
2024-12-08 21:19:08,328 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2024-12-08 21:19:08,333 | WARNING | Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\PythonProject12\tests_12_4.py", line 25, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "C:\Users\User\PycharmProjects\PythonProject12\module_12_4.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-12-08 21:19:08,333 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2024-12-08 21:19:08,340 | WARNING | Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\PythonProject12\tests_12_4.py", line 14, in test_walk
    runner = Runner("Вася", -5)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\PythonProject12\module_12_4.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

